# Generated by Django 4.2 on 2023-04-24 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='type',
            new_name='habit_type',
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_count_unit',
            field=models.CharField(default='ml', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_rep',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_rep_unit',
            field=models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='Week', max_length=50),
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('goal_done', models.IntegerField(default=0)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_url', to='mainapp.habit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='habitrecord',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='unique datelog'),
        ),
    ]
