# Generated by Django 4.2 on 2023-04-24 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_rename_type_habit_habit_type_habit_goal_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='habittype',
            options={},
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.habittype'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habittype',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habittype',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
