# Generated by Django 4.2 on 2023-04-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_habittype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habit_url', to='mainapp.habit'),
        ),
    ]
